"""
Django settings for appointment_management project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u@34(5&j-axzmt%ugzam24^_4_1!nyu%1)30ki_^hvvhooati_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpush',
    'users',
    'appointments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appointment_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            # 'loaders': [
            #     'django.template.loaders.cached.Loader',
            # ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appointment_management.context_processor.webpush_processor',
                'appointment_management.context_processor.user_processor',
                'appointment_management.context_processor.admin_header_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'appointment_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # {
    #     'NAME': 'appointment_management.validators.NumberValidator',
    #     'OPTIONS': {
    #         'min_digits': 1,
    #     }
    # },
    # {
    #     'NAME': 'appointment_management.validators.UppercaseValidator',
    # },
    # {
    #     'NAME': 'appointment_management.validators.LowercaseValidator',
    # },
    # {
    #     'NAME': 'appointment_management.validators.SymbolValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Settings

EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = os.getenv('EMAIL_HOST','smtp.gmail.com')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER','appt.demo@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD','dummypass')

# Web notifications settings
# Vapid keys from: https://web-push-codelab.glitch.me/

WEBPUSH_SETTINGS = {
   "VAPID_PUBLIC_KEY": "BO50S2D5OBqGawvrzUl79DleSjRuF1F4dpgBf42JNt5HHg_31WHO0xCJ0y494I4vKgVecTeeIPBAD2pQgFl3D50",
   "VAPID_PRIVATE_KEY": "vw-nlSlBPlSaT4AkKSayUlFY8YgsfdLEVe1EGeb39TU",
   "VAPID_ADMIN_EMAIL": 'skinstudiobyrasnakapoor@gmail.com'
}


# Authorization settings
LOGIN_URL = '/users/loginprev/'
LOGOUT_REDIRECT_URL = '/'
PASSWORD_RESET_TIMEOUT = 1800   # The number of seconds a password reset link is valid for.
