# Generated by Django 3.2.7 on 2021-09-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(choices=[(0, 'Open'), (1, 'Booked'), (2, 'Completed'), (4, 'Rescheduled'), (5, 'Cancelled')], default=0)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True)),
                ('Type', models.CharField(blank=True, choices=[(0, 'Skin'), (1, 'Lazer'), (2, 'Fat')], default='', max_length=50)),
                ('BillingAmount', models.FloatField(blank=True, default=0.0)),
                ('PaymentStatus', models.IntegerField(choices=[(0, 'Due'), (1, 'Paid'), (2, 'Unset')], default=2)),
                ('Notes', models.CharField(blank=True, default='', max_length=300)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile')),
                ('Patient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.patientprofile')),
            ],
        ),
    ]
