# Generated by Django 3.2.7 on 2021-09-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
