# Generated by Django 3.2.7 on 2021-09-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('appointments', '0002_alter_appointment_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='patient', to='users.patientprofile'),
        ),
    ]
