# Generated by Django 3.2.7 on 2021-09-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210930_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Type',
            new_name='apt_type',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='BillingAmount',
            new_name='billing_amount',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='PaymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Status',
            new_name='status',
        ),
    ]
