# Generated by Django 3.2.7 on 2021-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210930_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apt_type',
            field=models.CharField(blank=True, choices=[('Skin', 'Skin'), ('Lazer', 'Lazer'), ('Fat', 'Fat')], default='', max_length=50),
        ),
    ]
