# Generated by Django 3.2.7 on 2021-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_apt_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Booked'), (2, 'Completed'), (3, 'Cancelled')], default=0),
        ),
    ]
