# Generated by Django 3.2.7 on 2021-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
