# Generated by Django 3.2.7 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointmenttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Booked'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Checked In'), (5, 'Missed')], default=0),
        ),
    ]
